# Required metadata
sonar.projectKey=microdegree-project
sonar.projectName=Microdegree App
sonar.projectVersion=1.0

# Path to the source directories (usually '.' for root, or 'src' for Java/Node apps)
sonar.sources=.

# Exclude directories you don't want scanned (like node_modules, tests, or builds)
sonar.exclusions=node_modules/**, dist/**, **/*.test.js